--MySQL Script generated by MySQL Workbench
--03 / 31 / 18 22: 18: 52
--Model: New Model    Version: 1.0
--MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS= @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS= @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE= @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
    --Schema rtusdb
-- -----------------------------------------------------
    DROP SCHEMA IF EXISTS`rtusdb`;

-- -----------------------------------------------------
    --Schema rtusdb
-- -----------------------------------------------------
    CREATE SCHEMA IF NOT EXISTS`rtusdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE`rtusdb`;

-- -----------------------------------------------------
    --Table`rtusdb`.`t_enterprise`
-- -----------------------------------------------------
    DROP TABLE IF EXISTS`rtusdb`.`t_enterprise`;

CREATE TABLE IF NOT EXISTS`rtusdb`.`t_enterprise`(
    `id` VARCHAR(25) NOT NULL COMMENT '企业ID。企业上下级关系通过企业ID描述.格式KAABBBBCCCCDDDDEEEEFFFF',
    `name` VARCHAR(255) NOT NULL COMMENT '企业名称',
    `addr` VARCHAR(255) NULL COMMENT '企业地址',
    `number` VARCHAR(255) NULL COMMENT '企业营业执照号码',
    `introduction` VARCHAR(255) NULL COMMENT '企业介绍',
    `logo_pic_path` VARCHAR(255) NULL COMMENT '企业LOGO照片地址',
    `business_license_pic_path` VARCHAR(255) NULL COMMENT '企业营业执照照片路径',
    `certification` TINYINT NULL DEFAULT 0 COMMENT '实名认证. 0--未认证  1--提交认证  2--已认证',
    `status` TINYINT NULL DEFAULT 1 COMMENT '企业状态   0--已失效 1--正常使用中',
    `title_en` TINYINT NULL DEFAULT 0 COMMENT '系统显示使能  0--不显示 1--显示',
    `title_name` VARCHAR(255) NULL COMMENT '系统标题显示名称',
    `title_pic_path` VARCHAR(255) NULL COMMENT '标题图路径',
    PRIMARY KEY(`id`),
    UNIQUE INDEX`str_ent_name_UNIQUE`(`name` ASC),
    UNIQUE INDEX`id_enterprise_UNIQUE`(`id` ASC))
ENGINE = InnoDB
COMMENT = '企业组织表';


-- -----------------------------------------------------
    --Table`rtusdb`.`t_role`
-- -----------------------------------------------------
    DROP TABLE IF EXISTS`rtusdb`.`t_role`;

CREATE TABLE IF NOT EXISTS`rtusdb`.`t_role`(
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '角色ID',
    `name` VARCHAR(45) NOT NULL COMMENT '角色名',
    `introduce` VARCHAR(255) NULL COMMENT '角色介绍',
    `t_enterprise_id` VARCHAR(25) NOT NULL COMMENT '创建该权限的企业ID。',
    `power` VARCHAR(2048) NULL COMMENT '权限标识码。*代表所有权限,多个权限组合用逗号隔开。比如：createdevice,renamegroup',
    PRIMARY KEY(`id`),
    UNIQUE INDEX`role_id_UNIQUE`(`id` ASC),
    INDEX`fk_t_role_t_enterprise1_idx`(`t_enterprise_id` ASC),
    CONSTRAINT`fk_t_role_t_enterprise1`
    FOREIGN KEY(`t_enterprise_id`)
    REFERENCES`rtusdb`.`t_enterprise`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
    --Table`rtusdb`.`t_user`
-- -----------------------------------------------------
    DROP TABLE IF EXISTS`rtusdb`.`t_user`;

CREATE TABLE IF NOT EXISTS`rtusdb`.`t_user`(
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    `account` VARCHAR(45) NOT NULL COMMENT '账号',
    `phone` VARCHAR(45) NULL COMMENT '手机号',
    `name` VARCHAR(45) NULL COMMENT '真实姓名',
    `email` VARCHAR(45) NULL COMMENT '邮箱',
    `address` VARCHAR(45) NULL COMMENT '地址',
    `number` VARCHAR(45) NULL COMMENT '身份证号',
    `password` VARCHAR(45) NULL COMMENT '登陆密码，password=MD5(pass).pass为用户实际密码',
    `certification` TINYINT NOT NULL DEFAULT 0 COMMENT '认证状态\n0--未认证 1--认证申请  2--认证通过 ',
    `t_role_id` BIGINT NOT NULL,
    `t_enterprise_id` VARCHAR(25) NOT NULL,
    UNIQUE INDEX`str_login_name_UNIQUE`(`account` ASC),
    UNIQUE INDEX`user_id_UNIQUE`(`id` ASC),
    PRIMARY KEY(`id`),
    INDEX`fk_t_user_t_role1_idx`(`t_role_id` ASC),
    INDEX`fk_t_user_t_enterprise1_idx`(`t_enterprise_id` ASC),
    CONSTRAINT`fk_t_user_t_role1`
    FOREIGN KEY(`t_role_id`)
    REFERENCES`rtusdb`.`t_role`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT`fk_t_user_t_enterprise1`
    FOREIGN KEY(`t_enterprise_id`)
    REFERENCES`rtusdb`.`t_enterprise`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '用户表';


-- -----------------------------------------------------
    --Table`rtusdb`.`t_operation_record`
-- -----------------------------------------------------
    DROP TABLE IF EXISTS`rtusdb`.`t_operation_record`;

CREATE TABLE IF NOT EXISTS`rtusdb`.`t_operation_record`(
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '操作记录ID',
    `time` DATETIME NOT NULL COMMENT '操作时间',
    `opname` VARCHAR(255) NOT NULL COMMENT '操作名称',
    `opparam` VARCHAR(255) NULL COMMENT '操作详细信息',
    `t_user_id` BIGINT NOT NULL,
    PRIMARY KEY(`id`),
    UNIQUE INDEX`id_oprecord_UNIQUE`(`id` ASC),
    INDEX`fk_t_operation_record_t_user1_idx`(`t_user_id` ASC),
    CONSTRAINT`fk_t_operation_record_t_user1`
    FOREIGN KEY(`t_user_id`)
    REFERENCES`rtusdb`.`t_user`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '操作记录表';


-- -----------------------------------------------------
    --Table`rtusdb`.`t_device_type`
-- -----------------------------------------------------
    DROP TABLE IF EXISTS`rtusdb`.`t_device_type`;

CREATE TABLE IF NOT EXISTS`rtusdb`.`t_device_type`(
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '设备配置ID',
    `name` VARCHAR(45) NOT NULL COMMENT '设备分类名。建议命名方式：项目名_Tn 如:  SK211_T1',
    `setup_type` VARCHAR(1024) NULL COMMENT 'setup类型',
    `setup_caption` VARCHAR(1024) NULL COMMENT 'setup显示的名称',
    `setup_suffix` VARCHAR(1024) NULL COMMENT 'setup显示的后缀',
    `setup_min` VARCHAR(1024) NULL COMMENT 'setup最小值',
    `setup_max` VARCHAR(1024) NULL COMMENT 'setup最大值',
    `setup_user_visible` INT NULL COMMENT 'setup参数区普通用户可视个数',
    `setup_admin_visible` INT NULL COMMENT 'setup参数区管理员可见个数。',
    `test_type` VARCHAR(1024) NULL COMMENT 'test类型',
    `test_caption` VARCHAR(1024) NULL COMMENT 'test显示名称',
    `test_suffix` VARCHAR(1024) NULL COMMENT 'test显示的后缀',
    `test_save_enable` TINYINT(1) NULL COMMENT 'test保存使能',
    `test_save_interval` INT NULL COMMENT '保存test间隔',
    `test_user_visible` INT NULL COMMENT '测试数据区普通用户可视个数',
    `test_admin_visible` INT NULL COMMENT '测试数据区管理员用户可视个数',
    `ctrl_user_en` TINYINT(1) NULL COMMENT '普通用户允许控制与否',
    `ctrl_admin_en` TINYINT(1) NULL COMMENT '管理员用户允许控制否',
    `record_user_en` TINYINT(1) NULL COMMENT '普通用户允许记录查询与否',
    `record_admin_en` TINYINT(1) NULL COMMENT '管理员用户允许记录查询与否',
    `bundling_iccid_en` TINYINT(1) NULL COMMENT 'ICCID绑定使能',
    UNIQUE INDEX`id_t_device_config_UNIQUE`(`id` ASC),
    UNIQUE INDEX`str_device_type_name_UNIQUE`(`name` ASC),
    PRIMARY KEY(`id`))
ENGINE = InnoDB
COMMENT = '设备分类配置表';


-- -----------------------------------------------------
    --Table`rtusdb`.`t_device`
-- -----------------------------------------------------
    DROP TABLE IF EXISTS`rtusdb`.`t_device`;

CREATE TABLE IF NOT EXISTS`rtusdb`.`t_device`(
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '设备ID.',
    `psn` BIGINT NOT NULL COMMENT '设备序列号PSN',
    `name` VARCHAR(45) NOT NULL COMMENT '设备名称',
    `addr` VARCHAR(45) NULL COMMENT '设备安装地址',
    `longitude` DECIMAL(10, 7) NULL COMMENT '设备安装地址经度',
    `latitude` DECIMAL(10, 7) NULL COMMENT '设备安装地址纬度',
    `life_cycle` INT NULL COMMENT '设备生命周期。0--已到期停机  n--n天后到期',
    `life_start` DATE NULL COMMENT '设备开始时间。当前计费周期开始时间',
    `life_end` DATE NULL COMMENT '设备到期时间。当前计费周期截止时间',
    `iccid` VARCHAR(25) NULL COMMENT '设备使用的手机卡ICCID号',
    `imei` VARCHAR(25) NULL COMMENT '设备通讯模块的IMEI或ICCID码',
    `repair_status` TINYINT NULL COMMENT '维修状态：0--正常  1--报修中  2--修理中  3--已修好待验证 4--已报废',
    `t_device_type_id` BIGINT NOT NULL DEFAULT 0 COMMENT '当前所属设备分类ID',
    `expected_lifecycle` INT NOT NULL DEFAULT 0 COMMENT '期望申请续期时间，单位：天。当非0时表明有延期申请，当执行延期时，变更life-end和lifecycle，再把expected_cycle置0即可。',
    `renewal_ct` INT NOT NULL DEFAULT 0 COMMENT '已续期次数',
    `t_enterprise_id` VARCHAR(25) NOT NULL,
    PRIMARY KEY(`id`),
    UNIQUE INDEX`i_device_psn_UNIQUE`(`psn` ASC),
    INDEX`fk_t_device_t_device_type1_idx`(`t_device_type_id` ASC),
    INDEX`fk_t_device_t_enterprise1_idx`(`t_enterprise_id` ASC),
    CONSTRAINT`fk_t_device_t_device_type1`
    FOREIGN KEY(`t_device_type_id`)
    REFERENCES`rtusdb`.`t_device_type`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT`fk_t_device_t_enterprise1`
    FOREIGN KEY(`t_enterprise_id`)
    REFERENCES`rtusdb`.`t_enterprise`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '设备信息表';


-- -----------------------------------------------------
    --Table`rtusdb`.`t_group`
-- -----------------------------------------------------
    DROP TABLE IF EXISTS`rtusdb`.`t_group`;

CREATE TABLE IF NOT EXISTS`rtusdb`.`t_group`(
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '组ID',
    `name` VARCHAR(45) NOT NULL COMMENT '组名',
    `t_enterprise_id` VARCHAR(25) NOT NULL COMMENT '所属企业ID',
    PRIMARY KEY(`id`),
    UNIQUE INDEX`name_t_enterprise_id_UNIQUE`(`name` ASC, `t_enterprise_id` ASC),
    INDEX`fk_t_device_group_t_enterprise1_idx`(`t_enterprise_id` ASC),
    CONSTRAINT`fk_t_device_group_t_enterprise1`
    FOREIGN KEY(`t_enterprise_id`)
    REFERENCES`rtusdb`.`t_enterprise`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '分组表';


-- -----------------------------------------------------
    --Table`rtusdb`.`t_measure_record`
-- -----------------------------------------------------
    DROP TABLE IF EXISTS`rtusdb`.`t_measure_record`;

CREATE TABLE IF NOT EXISTS`rtusdb`.`t_measure_record`(
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '测量记录ID',
    `time` DATETIME NULL COMMENT '记录时间',
    `run` INT NULL COMMENT '测量记录run值',
    `mode` INT NULL COMMENT '测量记录mode值',
    `alarm` INT NULL COMMENT '测量记录alarm值',
    `error` INT NULL COMMENT '测量记录error值',
    `other` VARCHAR(2048) NULL COMMENT '测量记录其他值',
    `t_device_id` BIGINT NOT NULL COMMENT '设备ID',
    PRIMARY KEY(`id`),
    INDEX`fk_t_measure_record_t_device1_idx`(`t_device_id` ASC),
    CONSTRAINT`fk_t_measure_record_t_device1`
    FOREIGN KEY(`t_device_id`)
    REFERENCES`rtusdb`.`t_device`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '测量记录表';


-- -----------------------------------------------------
    --Table`rtusdb`.`t_repair_order`
-- -----------------------------------------------------
    DROP TABLE IF EXISTS`rtusdb`.`t_repair_order`;

CREATE TABLE IF NOT EXISTS`rtusdb`.`t_repair_order`(
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '维修单ID',
    `t_device_id` BIGINT NOT NULL COMMENT '设备ID',
    `status` TINYINT NOT NULL DEFAULT 0 COMMENT '维修单状态：0--已修好  1--报修中  2--修理中  3--已修好待验证 4--已报废',
    `problem` VARCHAR(255) NULL COMMENT '问题描述',
    `contact_way` VARCHAR(255) NULL COMMENT '提问者联系方式',
    `t_user_pro_id` BIGINT NOT NULL COMMENT '报修者ID',
    `t_user_sol_id` BIGINT NOT NULL COMMENT '维修者ID',
    `solutions` VARCHAR(255) NULL COMMENT '解决措施',
    PRIMARY KEY(`id`),
    INDEX`fk_t_repair_order_t_device1_idx`(`t_device_id` ASC),
    INDEX`fk_t_repair_order_t_user1_idx`(`t_user_pro_id` ASC),
    INDEX`fk_t_repair_order_t_user2_idx`(`t_user_sol_id` ASC),
    CONSTRAINT`fk_t_repair_order_t_device1`
    FOREIGN KEY(`t_device_id`)
    REFERENCES`rtusdb`.`t_device`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT`fk_t_repair_order_t_user1`
    FOREIGN KEY(`t_user_pro_id`)
    REFERENCES`rtusdb`.`t_user`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT`fk_t_repair_order_t_user2`
    FOREIGN KEY(`t_user_sol_id`)
    REFERENCES`rtusdb`.`t_user`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '维修单';


-- -----------------------------------------------------
    --Table`rtusdb`.`t_device_group`
-- -----------------------------------------------------
    DROP TABLE IF EXISTS`rtusdb`.`t_device_group`;

CREATE TABLE IF NOT EXISTS`rtusdb`.`t_device_group`(
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID',
    `t_device_id` BIGINT NOT NULL COMMENT '设备ID，具有唯一性，一个设备只能关联一个分组',
    `t_group_id` BIGINT NOT NULL COMMENT '分组ID',
    PRIMARY KEY(`id`),
    INDEX`fk_t_device_group_t_device1_idx`(`t_device_id` ASC),
    INDEX`fk_t_device_group_t_group1_idx`(`t_group_id` ASC),
    UNIQUE INDEX`t_device_id_UNIQUE`(`t_device_id` ASC),
    CONSTRAINT`fk_t_device_group_t_device1`
    FOREIGN KEY(`t_device_id`)
    REFERENCES`rtusdb`.`t_device`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT`fk_t_device_group_t_group1`
    FOREIGN KEY(`t_group_id`)
    REFERENCES`rtusdb`.`t_group`(`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '设备与分组关联表';


SET SQL_MODE =@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS =@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS =@OLD_UNIQUE_CHECKS;
